// Comprehensive data models and seed datasets for the NXT VIE Admin Panel.
// Provides live Firestore sync with rich fallback models.

import type { Order, OrderStatus, PaymentStatus } from "@/types/order";
import type { Coupon } from "@/types/common";
import type { Product, Category } from "@/types/product";
import type { Review, ReviewStatus } from "@/types/review";
import type { ShippingProvider, Shipment, ShippingLog } from "@/types/delivery";
import type { Customer, AdminUser, AdminRoleDefinition, AdminPermission } from "@/types/user";
import type { AdminAppSettings } from "@/types/settings";

export interface DashboardStats {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  totalCustomers: number;
  pendingOrdersCount: number;
  pendingReviewsCount: number;
  lowStockCount: number;
  averageOrderValue: number;
  recentOrders: Order[];
  pendingReviews: Review[];
  stockOverview: {
    id: string;
    name: string;
    sku: string;
    image: string;
    stock: number;
    status: "In Stock" | "Low Stock" | "Out of Stock";
    price: number;
  }[];
  statusBreakdown: Record<string, number>;
  revenueTrend: { date: string; amount: number; orders: number }[];
}

// ─── Default Settings ───────────────────────────────────────────
export const DEFAULT_SETTINGS: AdminAppSettings = {
  general: {
    storeName: "NXTVIE",
    storeTagline: "Modern Menswear for New Generations",
    storeLogoUrl: "/images/nxtvie/banner-urban-essentials.jpg",
    supportEmail: "care@nxtvie.com",
    supportPhone: "+91 80 4920 1800",
    storeAddress: "NXTVIE Fashion Labs, Indiranagar 100ft Road, Bengaluru 560038, Karnataka, India",
    currency: "INR",
    currencySymbol: "₹",
    taxRatePercent: 12,
    taxIncludedInPrice: true,
  },
  store: {
    lowStockThreshold: 10,
    freeShippingThreshold: 999,
    standardShippingFee: 99,
    priorityShippingFee: 150,
    codAvailable: true,
    returnWindowDays: 7,
    autoApproveReviews: false,
    maxOrderQuantityPerItem: 5,
  },
  notifications: {
    emailOnNewOrder: true,
    emailOnDelivered: true,
    smsOnShipping: true,
    alertOnLowStock: true,
    alertOnPaymentFailure: true,
    adminNotificationEmail: "operations@nxtvie.com",
    notifyOnPendingReview: true,
  },
  updatedAt: "2026-10-01T00:00:00Z",
};

// ─── Categories ────────────────────────────────────────────────
export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    slug: "t-shirts",
    name: "T-Shirts",
    title: "Heavyweight Graphic & Blank Tees",
    tagline: "280 GSM combed organic cotton silhouettes",
    image: "/images/nxtvie/cat-tshirts.jpg",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-2",
    slug: "shirts",
    name: "Shirts",
    title: "Relaxed Camp Collar & Oxford Shirts",
    tagline: "Tactile textured linen and twill weaves",
    image: "/images/nxtvie/cat-shirts.jpg",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-3",
    slug: "hoodies",
    name: "Hoodies",
    title: "450 GSM French Terry Pullovers",
    tagline: "Oversized draping with double-layered hoods",
    image: "/images/nxtvie/cat-hoodies.jpg",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat-4",
    slug: "bottoms",
    name: "Bottoms",
    title: "Pleated Trousers & Cargo Pants",
    tagline: "Structured cuts tailored for modern movement",
    image: "/images/nxtvie/cat-bottoms.jpg",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "cat-5",
    slug: "jackets",
    name: "Jackets",
    title: "Utility Overshirts & Bombers",
    tagline: "Trans-seasonal outerwear engineered to last",
    image: "/images/nxtvie/cat-jackets.jpg",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "cat-6",
    slug: "accessories",
    name: "Accessories",
    title: "Caps, Bags & Leather Goods",
    tagline: "Curated accents to elevate any ensemble",
    image: "/images/nxtvie/product-cap-hd.jpg",
    sortOrder: 6,
    isActive: true,
  },
];

// ─── Coupons ───────────────────────────────────────────────────
export const MOCK_COUPONS = [
  {
    id: "coup-1",
    code: "NEXT10",
    description: "10% off for first-time shoppers",
    type: "percentage" as const,
    value: 10,
    minOrderValue: 999,
    maxDiscount: 500,
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    usageCount: 142,
    usageLimit: 1000,
    isActive: true,
  },
  {
    id: "coup-2",
    code: "NXTVIE20",
    description: "20% off on orders above ₹2,499",
    type: "percentage" as const,
    value: 20,
    minOrderValue: 2499,
    maxDiscount: 1000,
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    usageCount: 89,
    usageLimit: 500,
    isActive: true,
  },
  {
    id: "coup-3",
    code: "FREESHIP",
    description: "Complimentary priority shipping",
    type: "fixed" as const,
    value: 150,
    minOrderValue: 799,
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    usageCount: 64,
    usageLimit: 200,
    isActive: true,
  },
];

// ─── Products Catalogue ────────────────────────────────────────
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    slug: "oversized-t-shirt",
    title: "Oversized T-Shirt",
    price: 1299,
    originalPrice: 1599,
    sku: "NV-TS-001",
    image: "/images/nxtvie/product-oversized-tee-hd.jpg",
    images: ["/images/nxtvie/product-oversized-tee-hd.jpg", "/images/nxtvie/product-minimal-logo-tee-hd.jpg"],
    category: "T-Shirts",
    collections: ["essentials", "oversized-fit"],
    badge: "Bestseller",
    colors: [
      { name: "Pitch Black", hex: "#181818" },
      { name: "Mineral Grey", hex: "#7A7670" },
      { name: "Bone White", hex: "#EDEAE1" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "Heavyweight 280 GSM combed organic cotton oversized tee with signature raw cut hem and drop shoulder fit.",
    details: ["280 GSM single jersey", "Drop shoulder boxy silhouette", "Pre-shrunk fabric", "High ribbed neckband"],
    fabricCare: ["Machine wash cold with like colors", "Turn inside out before wash", "Warm iron if needed"],
    fit: "Oversized Relaxed Boxy Fit",
    rating: 4.9,
    reviewCount: 48,
    inStock: true,
    totalStock: 120,
    lowStockThreshold: 15,
    featured: true,
    isActive: true,
    createdAt: "2026-10-01T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "prod-2",
    slug: "relaxed-fit-jeans",
    title: "Relaxed Fit Jeans",
    price: 1899,
    originalPrice: 2299,
    sku: "NV-JN-002",
    image: "/images/nxtvie/product-cargo-pants-hd.jpg",
    images: ["/images/nxtvie/product-cargo-pants-hd.jpg"],
    category: "Bottoms",
    collections: ["denim", "everyday-wear"],
    badge: "Trending",
    colors: [
      { name: "Vintage Indigo", hex: "#2C3E50" },
      { name: "Faded Grey", hex: "#4A4E54" },
    ],
    sizes: ["30", "32", "34", "36"],
    description: "Premium Japanese twill relaxed straight cut jeans tailored for all-day comfort and timeless street aesthetic.",
    details: ["13.5 oz ring-spun cotton", "Custom matte silver rivets", "Five pocket design", "Relaxed straight leg"],
    fabricCare: ["Cold machine wash", "Do not tumble dry", "Wash inside out"],
    fit: "Relaxed Straight Cut",
    rating: 4.8,
    reviewCount: 32,
    inStock: true,
    totalStock: 8, // Low Stock
    lowStockThreshold: 10,
    featured: true,
    isActive: true,
    createdAt: "2026-09-30T10:00:00Z",
    updatedAt: "2026-10-01T09:00:00Z",
  },
  {
    id: "prod-3",
    slug: "linen-shirt",
    title: "Linen Shirt",
    price: 1699,
    originalPrice: 1999,
    sku: "NV-SH-003",
    image: "/images/nxtvie/product-relaxed-fit-shirt-hd.jpg",
    images: ["/images/nxtvie/product-relaxed-fit-shirt-hd.jpg"],
    category: "Shirts",
    collections: ["summer-resort", "linen-craft"],
    badge: "New",
    colors: [
      { name: "Raw Ivory", hex: "#F4F0E8" },
      { name: "Sand Stone", hex: "#D2C5B3" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "100% French flax pure linen camp collar shirt with mother of pearl finish buttons. Breathable and airy.",
    details: ["100% pure linen", "Camp collar silhouette", "Double stitched pocket", "Natural textured slub"],
    fabricCare: ["Hand wash or gentle cycle", "Hang dry in shade", "Steam iron"],
    fit: "Casual Camp Fit",
    rating: 4.7,
    reviewCount: 19,
    inStock: false,
    totalStock: 0, // Out of Stock
    lowStockThreshold: 10,
    featured: false,
    isActive: false,
    createdAt: "2026-09-29T14:00:00Z",
    updatedAt: "2026-10-01T10:00:00Z",
  },
  {
    id: "prod-4",
    slug: "cargo-pants",
    title: "Cargo Pants",
    price: 1999,
    originalPrice: 2499,
    sku: "NV-CP-004",
    image: "/images/nxtvie/cat-bottoms.jpg",
    images: ["/images/nxtvie/cat-bottoms.jpg"],
    category: "Bottoms",
    collections: ["streetwear", "utility"],
    badge: null,
    colors: [
      { name: "Army Olive", hex: "#4B5320" },
      { name: "Charcoal Black", hex: "#1C1C1C" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "Multi-pocket tactical utility cargo trousers made with ripstop cotton twill and adjustable ankle cords.",
    details: ["Durable ripstop cotton", "6 ergonomic utility pockets", "Elasticated back waistband", "Ankle toggle cinches"],
    fabricCare: ["Machine wash warm", "Hang dry", "Do not iron prints"],
    fit: "Tapered Utility Fit",
    rating: 4.9,
    reviewCount: 41,
    inStock: true,
    totalStock: 35,
    lowStockThreshold: 10,
    featured: true,
    isActive: true,
    createdAt: "2026-09-28T16:00:00Z",
    updatedAt: "2026-09-28T16:00:00Z",
  },
  {
    id: "prod-5",
    slug: "hoodie-sweatshirt",
    title: "Hoodie Sweatshirt",
    price: 2299,
    originalPrice: 2799,
    sku: "NV-HD-005",
    image: "/images/nxtvie/product-core-hoodie-hd.jpg",
    images: ["/images/nxtvie/product-core-hoodie-hd.jpg"],
    category: "Hoodies",
    collections: ["winter-heavy", "essentials"],
    badge: "Trending",
    colors: [
      { name: "Onyx Black", hex: "#111111" },
      { name: "Heather Grey", hex: "#8A8D8F" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "450 GSM ultra-heavyweight brushed French terry cotton pullover hoodie with dual layer hood and hidden kangaroo pocket.",
    details: ["450 GSM loopback cotton", "No-drawstring structured hood", "Seamless kangaroo pouch", "Double rib side gussets"],
    fabricCare: ["Cold wash only", "Lay flat to dry", "Do not bleach"],
    fit: "Oversized Draped Fit",
    rating: 5.0,
    reviewCount: 64,
    inStock: true,
    totalStock: 5, // Low Stock
    lowStockThreshold: 10,
    featured: true,
    isActive: true,
    createdAt: "2026-09-27T12:00:00Z",
    updatedAt: "2026-10-01T11:00:00Z",
  },
  {
    id: "prod-6",
    slug: "minimal-logo-tee",
    title: "Minimal Logo Tee",
    price: 899,
    originalPrice: 1199,
    sku: "NV-TS-006",
    image: "/images/nxtvie/product-minimal-logo-tee-hd.jpg",
    images: ["/images/nxtvie/product-minimal-logo-tee-hd.jpg"],
    category: "T-Shirts",
    collections: ["essentials"],
    badge: "New",
    colors: [
      { name: "Sand Beige", hex: "#E5E0D5" },
      { name: "Deep Black", hex: "#181818" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "Sand beige minimalist tee with subtle embroidered tonal logo and pre-shrunk luxury Japanese cotton weave.",
    details: ["240 GSM organic cotton", "Tonal micro-embroidery", "Standard streetwear fit"],
    fabricCare: ["Machine wash cold", "Dry in shade"],
    fit: "Streetwear Regular",
    rating: 4.8,
    reviewCount: 22,
    inStock: true,
    totalStock: 64,
    lowStockThreshold: 10,
    featured: false,
    isActive: true,
    createdAt: "2026-09-25T10:00:00Z",
    updatedAt: "2026-09-25T10:00:00Z",
  },
  {
    id: "prod-7",
    slug: "structured-wool-overshirt",
    title: "Structured Wool Overshirt",
    price: 3499,
    originalPrice: 4299,
    sku: "NV-JK-007",
    image: "/images/nxtvie/promo-jackets-hd.jpg",
    images: ["/images/nxtvie/promo-jackets-hd.jpg"],
    category: "Jackets",
    collections: ["outerwear", "winter-heavy"],
    badge: "Bestseller",
    colors: [{ name: "Espresso Brown", hex: "#3D2B1F" }],
    sizes: ["M", "L", "XL"],
    description: "Heavy wool blend overshirt with dual front flap pockets and horn buttons.",
    details: ["Wool blend exterior", "Cupro lined sleeves", "Custom horn buttons"],
    fabricCare: ["Dry clean only"],
    fit: "Boxy Layering Fit",
    rating: 4.9,
    reviewCount: 18,
    inStock: true,
    totalStock: 14,
    lowStockThreshold: 5,
    featured: true,
    isActive: true,
    createdAt: "2026-09-24T09:00:00Z",
    updatedAt: "2026-09-24T09:00:00Z",
  },
  {
    id: "prod-8",
    slug: "nxtvie-signature-cap",
    title: "NXTVIE Signature Cap",
    price: 699,
    originalPrice: 999,
    sku: "NV-AC-008",
    image: "/images/nxtvie/product-cap-hd.jpg",
    images: ["/images/nxtvie/product-cap-hd.jpg"],
    category: "Accessories",
    collections: ["accessories"],
    badge: null,
    colors: [{ name: "Pitch Black", hex: "#111111" }],
    sizes: ["One Size"],
    description: "6-panel washed cotton twill strapback cap with brass hardware.",
    details: ["100% cotton twill", "Curved visor", "Brass buckle strap"],
    fabricCare: ["Spot clean with damp cloth"],
    fit: "Adjustable Strapback",
    rating: 4.7,
    reviewCount: 15,
    inStock: true,
    totalStock: 40,
    lowStockThreshold: 10,
    featured: false,
    isActive: true,
    createdAt: "2026-09-22T11:00:00Z",
    updatedAt: "2026-09-22T11:00:00Z",
  },
];

// ─── Orders (Matching reference design) ─────────────────────────
export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-10245",
    orderNumber: "#NV10245",
    userId: "usr-1",
    items: [
      {
        productId: "prod-1",
        title: "Oversized T-Shirt",
        sku: "NV-TS-001",
        price: 1299,
        quantity: 1,
        selectedSize: "L",
        selectedColor: "Pitch Black",
        image: "/images/nxtvie/product-oversized-tee-hd.jpg",
      },
      {
        productId: "prod-5",
        title: "Hoodie Sweatshirt",
        sku: "NV-HD-005",
        price: 2299,
        quantity: 1,
        selectedSize: "L",
        selectedColor: "Onyx Black",
        image: "/images/nxtvie/product-core-hoodie-hd.jpg",
      },
    ],
    subtotal: 3598,
    discount: 100,
    shipping: 0,
    total: 3498,
    status: "delivered",
    statusHistory: [
      { status: "pending", timestamp: "2026-09-28T09:00:00Z", note: "Order placed online" },
      { status: "processing", timestamp: "2026-09-28T11:30:00Z", note: "Verified and sent to warehouse" },
      { status: "packed", timestamp: "2026-09-29T14:00:00Z", note: "Packed in NXTVIE custom apparel box" },
      { status: "shipped", timestamp: "2026-09-30T10:00:00Z", note: "Handed over to BlueDart (AWB: BD-92810481)" },
      { status: "delivered", timestamp: "2026-10-01T14:15:00Z", note: "Delivered to customer with OTP verification" },
    ],
    paymentMethod: "Razorpay (UPI)",
    paymentStatus: "paid",
    razorpayOrderId: "order_R010245",
    razorpayPaymentId: "pay_R010245_1938",
    shippingAddress: {
      fullName: "Rahul Sharma",
      email: "rahul.sharma@example.com",
      phone: "+91 98765 43210",
      street: "Flat 402, Skyline Residency, 100ft Road, Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560038",
      country: "India",
    },
    deliveryMethod: "BlueDart Express",
    trackingNumber: "BD-92810481",
    trackingUrl: "https://www.bluedart.com/tracking?track=BD-92810481",
    createdAt: "2026-10-01T09:00:00Z",
    updatedAt: "2026-10-01T14:15:00Z",
  },
  {
    id: "ord-10244",
    orderNumber: "#NV10244",
    userId: "usr-2",
    items: [
      {
        productId: "prod-2",
        title: "Relaxed Fit Jeans",
        sku: "NV-JN-002",
        price: 1899,
        quantity: 1,
        selectedSize: "32",
        selectedColor: "Vintage Indigo",
        image: "/images/nxtvie/product-cargo-pants-hd.jpg",
      },
    ],
    subtotal: 1899,
    discount: 100,
    shipping: 0,
    total: 1799,
    status: "shipped",
    statusHistory: [
      { status: "pending", timestamp: "2026-09-29T16:00:00Z", note: "Order placed online" },
      { status: "processing", timestamp: "2026-09-30T09:00:00Z", note: "Items picked from rack" },
      { status: "shipped", timestamp: "2026-10-01T08:30:00Z", note: "Dispatched via Delhivery Air" },
    ],
    paymentMethod: "Razorpay (Credit Card)",
    paymentStatus: "paid",
    razorpayOrderId: "order_R010244",
    razorpayPaymentId: "pay_R010244_9182",
    shippingAddress: {
      fullName: "Karan Mehta",
      email: "karan.mehta@example.com",
      phone: "+91 98220 11223",
      street: "12, Silver Beach Apartments, Juhu",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400049",
      country: "India",
    },
    deliveryMethod: "Delhivery Air",
    trackingNumber: "DEL-84920194",
    trackingUrl: "https://www.delhivery.com/track/package/DEL-84920194",
    createdAt: "2026-10-01T08:30:00Z",
    updatedAt: "2026-10-01T08:30:00Z",
  },
  {
    id: "ord-10243",
    orderNumber: "#NV10243",
    userId: "usr-3",
    items: [
      {
        productId: "prod-1",
        title: "Oversized T-Shirt",
        sku: "NV-TS-001",
        price: 1299,
        quantity: 1,
        selectedSize: "M",
        selectedColor: "Mineral Grey",
        image: "/images/nxtvie/product-oversized-tee-hd.jpg",
      },
      {
        productId: "prod-3",
        title: "Linen Shirt",
        sku: "NV-SH-003",
        price: 1699,
        quantity: 1,
        selectedSize: "L",
        selectedColor: "Sand Stone",
        image: "/images/nxtvie/product-relaxed-fit-shirt-hd.jpg",
      },
      {
        productId: "prod-4",
        title: "Cargo Pants",
        sku: "NV-CP-004",
        price: 1999,
        quantity: 1,
        selectedSize: "L",
        selectedColor: "Army Olive",
        image: "/images/nxtvie/cat-bottoms.jpg",
      },
    ],
    subtotal: 4997,
    discount: 0,
    shipping: 0,
    total: 4997,
    status: "packed",
    statusHistory: [
      { status: "pending", timestamp: "2026-09-30T10:15:00Z", note: "Order placed online" },
      { status: "processing", timestamp: "2026-09-30T12:00:00Z", note: "Sent to packaging bench" },
      { status: "packed", timestamp: "2026-09-30T17:00:00Z", note: "Packed & sealed for courier pickup" },
    ],
    paymentMethod: "Razorpay (NetBanking)",
    paymentStatus: "paid",
    razorpayOrderId: "order_R010243",
    razorpayPaymentId: "pay_R010243_5510",
    shippingAddress: {
      fullName: "Amit Verma",
      email: "amit.verma@example.com",
      phone: "+91 99112 33445",
      street: "78, Golf Links, Lodhi Road",
      city: "New Delhi",
      state: "Delhi",
      postalCode: "110003",
      country: "India",
    },
    deliveryMethod: "Shiprocket Surface",
    trackingNumber: "SR-392019842",
    createdAt: "2026-09-30T10:15:00Z",
    updatedAt: "2026-09-30T17:00:00Z",
  },
  {
    id: "ord-10242",
    orderNumber: "#NV10242",
    userId: "usr-4",
    items: [
      {
        productId: "prod-1",
        title: "Oversized T-Shirt",
        sku: "NV-TS-001",
        price: 1299,
        quantity: 1,
        selectedSize: "S",
        selectedColor: "Bone White",
        image: "/images/nxtvie/product-oversized-tee-hd.jpg",
      },
      {
        productId: "prod-6",
        title: "Minimal Logo Tee",
        sku: "NV-TS-006",
        price: 899,
        quantity: 1,
        selectedSize: "S",
        selectedColor: "Deep Black",
        image: "/images/nxtvie/product-minimal-logo-tee-hd.jpg",
      },
    ],
    subtotal: 2198,
    discount: 0,
    shipping: 500, // express
    total: 2698,
    status: "processing",
    statusHistory: [
      { status: "pending", timestamp: "2026-09-30T14:00:00Z", note: "Order placed online" },
      { status: "processing", timestamp: "2026-09-30T16:00:00Z", note: "Inventory allocated" },
    ],
    paymentMethod: "Razorpay (UPI)",
    paymentStatus: "paid",
    razorpayOrderId: "order_R010242",
    razorpayPaymentId: "pay_R010242_1290",
    shippingAddress: {
      fullName: "Sneha Reddy",
      email: "sneha.reddy@example.com",
      phone: "+91 97401 22334",
      street: "Plot 89, Jubilee Hills Road No 36",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500033",
      country: "India",
    },
    deliveryMethod: "BlueDart Express",
    createdAt: "2026-09-30T14:00:00Z",
    updatedAt: "2026-09-30T16:00:00Z",
  },
  {
    id: "ord-10241",
    orderNumber: "#NV10241",
    userId: "usr-5",
    items: [
      {
        productId: "prod-4",
        title: "Cargo Pants",
        sku: "NV-CP-004",
        price: 1499,
        quantity: 1,
        selectedSize: "M",
        selectedColor: "Charcoal Black",
        image: "/images/nxtvie/cat-bottoms.jpg",
      },
    ],
    subtotal: 1499,
    discount: 0,
    shipping: 0,
    total: 1499,
    status: "cancelled",
    statusHistory: [
      { status: "pending", timestamp: "2026-09-29T11:00:00Z", note: "Order created" },
      { status: "cancelled", timestamp: "2026-09-29T11:45:00Z", note: "Customer changed delivery address" },
    ],
    paymentMethod: "Cash on Delivery",
    paymentStatus: "cancelled",
    shippingAddress: {
      fullName: "Vikram Singh",
      email: "vikram.singh@example.com",
      phone: "+91 99881 22334",
      street: "C-14, Malviya Nagar",
      city: "Jaipur",
      state: "Rajasthan",
      postalCode: "302017",
      country: "India",
    },
    deliveryMethod: "Standard COD",
    cancelReason: "Customer requested cancellation prior to packing",
    createdAt: "2026-09-29T11:00:00Z",
    updatedAt: "2026-09-29T11:45:00Z",
  },
];

// ─── Reviews (Pending, Approved, Rejected) ──────────────────────
export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    productTitle: "Oversized T-Shirt",
    productSlug: "oversized-t-shirt",
    productImage: "/images/nxtvie/product-oversized-tee-hd.jpg",
    userId: "usr-rev-1",
    userName: "Arjun Patel",
    userEmail: "arjun.patel@example.com",
    userAvatar: "/images/nxtvie/gallery-1.jpg",
    rating: 5,
    title: "Unmatched Fabric Density",
    comment: "Great quality and perfect fit. Really love the 280 GSM weight, it drapes without clinging.",
    status: "pending",
    verifiedBuyer: true,
    sizePurchased: "L",
    createdAt: "2026-09-29T14:30:00Z",
  },
  {
    id: "rev-2",
    productId: "prod-2",
    productTitle: "Relaxed Fit Jeans",
    productSlug: "relaxed-fit-jeans",
    productImage: "/images/nxtvie/product-cargo-pants-hd.jpg",
    userId: "usr-rev-2",
    userName: "Rohit Kumar",
    userEmail: "rohit.k@example.com",
    userAvatar: "/images/nxtvie/gallery-2.jpg",
    rating: 5,
    title: "Premium Japanese Weave",
    comment: "Looks premium. Fabric is very good, soft yet sturdy. The fade on the vintage indigo is subtle.",
    status: "pending",
    verifiedBuyer: true,
    sizePurchased: "32",
    createdAt: "2026-09-28T10:15:00Z",
  },
  {
    id: "rev-3",
    productId: "prod-3",
    productTitle: "Linen Shirt",
    productSlug: "linen-shirt",
    productImage: "/images/nxtvie/product-relaxed-fit-shirt-hd.jpg",
    userId: "usr-rev-3",
    userName: "Neha Sharma",
    userEmail: "neha.s@example.com",
    userAvatar: "/images/nxtvie/gallery-3.jpg",
    rating: 4,
    title: "Breathable Camp Collar",
    comment: "Good design but size is a bit large for me. Suggest sizing down if you prefer tailored cuts.",
    status: "pending",
    verifiedBuyer: true,
    sizePurchased: "M",
    createdAt: "2026-09-27T18:00:00Z",
  },
  {
    id: "rev-4",
    productId: "prod-4",
    productTitle: "Cargo Pants",
    productSlug: "cargo-pants",
    productImage: "/images/nxtvie/cat-bottoms.jpg",
    userId: "usr-rev-4",
    userName: "Karan Mehta",
    userEmail: "karan.m@example.com",
    userAvatar: "/images/nxtvie/gallery-4.jpg",
    rating: 5,
    title: "Utility Perfection",
    comment: "Excellent material and fast delivery. Ankle toggle feature makes it pair great with chunky sneakers.",
    status: "pending",
    verifiedBuyer: true,
    sizePurchased: "L",
    createdAt: "2026-09-26T12:00:00Z",
  },
  {
    id: "rev-5",
    productId: "prod-5",
    productTitle: "Hoodie Sweatshirt",
    productSlug: "hoodie-sweatshirt",
    productImage: "/images/nxtvie/product-core-hoodie-hd.jpg",
    userId: "usr-rev-5",
    userName: "Priya Nair",
    userEmail: "priya.n@example.com",
    userAvatar: "/images/nxtvie/gallery-5.jpg",
    rating: 5,
    title: "Heaviest Hoodie in India",
    comment: "The double layered hood stays upright without sagging. French terry finish is so soft.",
    status: "approved",
    verifiedBuyer: true,
    sizePurchased: "XL",
    createdAt: "2026-09-24T16:00:00Z",
    moderatedBy: "Venkatesh",
    moderatedAt: "2026-09-25T09:00:00Z",
  },
  {
    id: "rev-6",
    productId: "prod-1",
    productTitle: "Oversized T-Shirt",
    productSlug: "oversized-t-shirt",
    productImage: "/images/nxtvie/product-oversized-tee-hd.jpg",
    userId: "usr-rev-6",
    userName: "Aarav Varma",
    userEmail: "aarav.v@example.com",
    userAvatar: "/images/nxtvie/gallery-6.jpg",
    rating: 5,
    title: "Heavy cotton feel is unreal",
    comment: "Easily one of the highest quality oversized silhouettes I have owned in India. Collar stays structured even after 3 washes.",
    status: "approved",
    verifiedBuyer: true,
    sizePurchased: "L",
    createdAt: "2026-09-20T11:00:00Z",
    moderatedBy: "Venkatesh",
    moderatedAt: "2026-09-20T14:00:00Z",
  },
  {
    id: "rev-7",
    productId: "prod-1",
    productTitle: "Oversized T-Shirt",
    productSlug: "oversized-t-shirt",
    productImage: "/images/nxtvie/product-oversized-tee-hd.jpg",
    userId: "usr-rev-7",
    userName: "Dev Malhotra",
    userEmail: "dev.m@example.com",
    rating: 1,
    title: "Wrong color delivered",
    comment: "Ordered black and received grey. Package was crushed upon delivery.",
    status: "rejected",
    moderationNotes: "Rejected due to logistics issue — customer support ticket #TK-849 opened and replacement sent.",
    verifiedBuyer: false,
    createdAt: "2026-09-18T10:00:00Z",
    moderatedBy: "Venkatesh",
    moderatedAt: "2026-09-18T15:00:00Z",
  },
];

// ─── Customers ─────────────────────────────────────────────────
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "usr-1",
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91 98765 43210",
    city: "Bengaluru",
    state: "Karnataka",
    accountStatus: "active",
    ordersCount: 4,
    totalSpent: 9840,
    registrationDate: "2026-06-15T00:00:00Z",
    lastActivity: "2026-10-01T14:15:00Z",
    segmentTier: "VIP",
    addresses: [
      {
        id: "addr-1",
        label: "Home",
        fullName: "Rahul Sharma",
        phone: "+91 98765 43210",
        street: "Flat 402, Skyline Residency, 100ft Road, Indiranagar",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560038",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    id: "usr-2",
    name: "Karan Mehta",
    email: "karan.mehta@example.com",
    phone: "+91 98220 11223",
    city: "Mumbai",
    state: "Maharashtra",
    accountStatus: "active",
    ordersCount: 3,
    totalSpent: 5990,
    registrationDate: "2026-07-20T00:00:00Z",
    lastActivity: "2026-10-01T08:30:00Z",
    segmentTier: "Regular",
    addresses: [
      {
        id: "addr-2",
        label: "Primary",
        fullName: "Karan Mehta",
        phone: "+91 98220 11223",
        street: "12, Silver Beach Apartments, Juhu",
        city: "Mumbai",
        state: "Maharashtra",
        postalCode: "400049",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    id: "usr-3",
    name: "Amit Verma",
    email: "amit.verma@example.com",
    phone: "+91 99112 33445",
    city: "New Delhi",
    state: "Delhi",
    accountStatus: "active",
    ordersCount: 5,
    totalSpent: 14250,
    registrationDate: "2026-05-10T00:00:00Z",
    lastActivity: "2026-09-30T17:00:00Z",
    segmentTier: "VIP",
    addresses: [
      {
        id: "addr-3",
        label: "Residence",
        fullName: "Amit Verma",
        phone: "+91 99112 33445",
        street: "78, Golf Links, Lodhi Road",
        city: "New Delhi",
        state: "Delhi",
        postalCode: "110003",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    id: "usr-4",
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    phone: "+91 97401 22334",
    city: "Hyderabad",
    state: "Telangana",
    accountStatus: "active",
    ordersCount: 2,
    totalSpent: 4890,
    registrationDate: "2026-08-01T00:00:00Z",
    lastActivity: "2026-09-30T16:00:00Z",
    segmentTier: "Regular",
  },
  {
    id: "usr-5",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    phone: "+91 99881 22334",
    city: "Jaipur",
    state: "Rajasthan",
    accountStatus: "suspended", // Example suspended user
    ordersCount: 1,
    totalSpent: 1499,
    registrationDate: "2026-09-12T00:00:00Z",
    lastActivity: "2026-09-29T11:45:00Z",
    segmentTier: "New",
    notes: "Account suspended due to repeated fraudulent COD cancellation pattern.",
  },
];

// ─── Shipping Providers ─────────────────────────────────────────
export const INITIAL_SHIPPING_PROVIDERS: ShippingProvider[] = [
  {
    id: "sp-1",
    name: "Shiprocket",
    slug: "shiprocket",
    description: "Automated multi-carrier aggregator with automated AWB generation and COD reconciliation.",
    isEnabled: true,
    isDefault: true,
    trackingUrlTemplate: "https://shiprocket.co/tracking/{{trackingNumber}}",
    logoUrl: "/images/nxtvie/cat-accessories.jpg",
    supportedRegions: ["All India (26,000+ Pin codes)", "Metro Priority", "Tier 2/3"],
    estimatedTransitDays: "2-4 Business Days",
    config: {
      baseUrl: "https://apiv2.shiprocket.in/v1/external",
      warehouseCode: "BLR_CENTRAL_01",
      isTestMode: false,
    },
  },
  {
    id: "sp-2",
    name: "Delhivery",
    slug: "delhivery",
    description: "Direct API integration with Delhivery Express Surface and Air logistics network.",
    isEnabled: true,
    isDefault: false,
    trackingUrlTemplate: "https://www.delhivery.com/track/package/{{trackingNumber}}",
    supportedRegions: ["Pan India", "Same-Day Metro Delhi/NCR, Mumbai, Bangalore"],
    estimatedTransitDays: "1-3 Business Days",
    config: {
      baseUrl: "https://track.delhivery.com/api/v1",
      warehouseCode: "DELHIVERY_WH_BLR",
      isTestMode: false,
    },
  },
  {
    id: "sp-3",
    name: "BlueDart Express",
    slug: "bluedart",
    description: "Premium express courier service for priority apparel orders and high-value cargo.",
    isEnabled: true,
    isDefault: false,
    trackingUrlTemplate: "https://www.bluedart.com/tracking?track={{trackingNumber}}",
    supportedRegions: ["Air Express Metros", "Major Hubs"],
    estimatedTransitDays: "24-48 Hours",
    config: {
      baseUrl: "https://api.bluedart.com/servlet/RoutingServlet",
      accountNumber: "BD-NXTVIE-8921",
      isTestMode: false,
    },
  },
  {
    id: "sp-4",
    name: "VRL Logistics",
    slug: "vrl_logistics",
    description: "Bulk consignment and warehouse distribution logistics across South & Western India.",
    isEnabled: false,
    isDefault: false,
    trackingUrlTemplate: "https://www.vrlgroup.in/track/{{trackingNumber}}",
    supportedRegions: ["South India", "Western Corridors"],
    estimatedTransitDays: "3-5 Business Days",
    config: {
      baseUrl: "https://api.vrlgroup.in/consignments",
      isTestMode: true,
    },
  },
];

// ─── Shipments ─────────────────────────────────────────────────
export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: "shp-1",
    orderId: "ord-10245",
    orderNumber: "#NV10245",
    customerName: "Rahul Sharma",
    destinationCity: "Bengaluru",
    provider: "bluedart",
    providerName: "BlueDart Express",
    trackingNumber: "BD-92810481",
    trackingUrl: "https://www.bluedart.com/tracking?track=BD-92810481",
    status: "delivered",
    shippedAt: "2026-09-30T10:00:00Z",
    deliveredAt: "2026-10-01T14:15:00Z",
    weight: 950,
    dimensions: { length: 30, width: 25, height: 8 },
    events: [
      { status: "picked_up", location: "Bengaluru Warehouse", timestamp: "2026-09-30T10:00:00Z", description: "Consignment picked up by courier partner" },
      { status: "in_transit", location: "Bangalore Sorting Hub", timestamp: "2026-09-30T18:00:00Z", description: "Processed through sorting facility" },
      { status: "out_for_delivery", location: "Indiranagar Hub", timestamp: "2026-10-01T08:30:00Z", description: "Out for delivery with rider Arun K." },
      { status: "delivered", location: "Indiranagar, Bengaluru", timestamp: "2026-10-01T14:15:00Z", description: "Delivered to recipient with digital signature" },
    ],
    createdAt: "2026-09-30T10:00:00Z",
    updatedAt: "2026-10-01T14:15:00Z",
  },
  {
    id: "shp-2",
    orderId: "ord-10244",
    orderNumber: "#NV10244",
    customerName: "Karan Mehta",
    destinationCity: "Mumbai",
    provider: "delhivery",
    providerName: "Delhivery Air",
    trackingNumber: "DEL-84920194",
    trackingUrl: "https://www.delhivery.com/track/package/DEL-84920194",
    status: "in_transit",
    shippedAt: "2026-10-01T08:30:00Z",
    estimatedDelivery: "2026-10-03",
    weight: 680,
    events: [
      { status: "picked_up", location: "Bengaluru Fulfillment Centre", timestamp: "2026-10-01T08:30:00Z", description: "Manifest created and parcel bagged" },
      { status: "in_transit", location: "Kempegowda Air Cargo", timestamp: "2026-10-01T13:00:00Z", description: "Boarded flight to Mumbai Chhatrapati Shivaji Hub" },
    ],
    createdAt: "2026-10-01T08:30:00Z",
    updatedAt: "2026-10-01T13:00:00Z",
  },
];

// ─── Shipping Logs ─────────────────────────────────────────────
export const INITIAL_SHIPPING_LOGS: ShippingLog[] = [
  {
    id: "log-1",
    providerId: "sp-1",
    providerName: "Shiprocket",
    action: "create_shipment",
    status: "success",
    orderNumber: "#NV10243",
    trackingNumber: "SR-392019842",
    message: "AWB generated successfully via Shiprocket API endpoint",
    timestamp: "2026-09-30T17:00:00Z",
  },
  {
    id: "log-2",
    providerId: "sp-2",
    providerName: "Delhivery",
    action: "create_shipment",
    status: "success",
    orderNumber: "#NV10244",
    trackingNumber: "DEL-84920194",
    message: "Manifest created and pickup scheduled for 10:00 AM",
    timestamp: "2026-10-01T08:30:00Z",
  },
  {
    id: "log-3",
    providerId: "sp-4",
    providerName: "VRL Logistics",
    action: "auth",
    status: "warning",
    message: "Test API credentials expiring in 5 days; production token required",
    timestamp: "2026-10-01T06:00:00Z",
  },
];

// ─── Admin Roles & Permissions ─────────────────────────────────
export const INITIAL_ROLES: AdminRoleDefinition[] = [
  {
    id: "role-super-admin",
    name: "Super Admin",
    slug: "super_admin",
    description: "Unrestricted operational, financial, and user management authority across all systems.",
    isSystem: true,
    userCount: 1,
    permissions: [
      "dashboard.view",
      "products.view", "products.create", "products.edit", "products.delete",
      "orders.view", "orders.edit", "orders.cancel",
      "customers.view", "customers.edit", "customers.suspend",
      "reviews.view", "reviews.approve", "reviews.reject", "reviews.delete",
      "payments.view", "payments.manage",
      "shipping.view", "shipping.manage",
      "admins.view", "admins.manage",
      "settings.manage",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-product-mgr",
    name: "Product Manager",
    slug: "product_manager",
    description: "Manage clothing catalog, sizing, pricing, images, categories, and inventory.",
    isSystem: true,
    userCount: 1,
    permissions: [
      "dashboard.view",
      "products.view", "products.create", "products.edit", "products.delete",
      "reviews.view", "reviews.approve", "reviews.reject",
      "categories.view", "categories.edit",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-order-mgr",
    name: "Order Manager",
    slug: "order_manager",
    description: "Manage order lifecycles, status updates, fulfillment, and cancellations.",
    isSystem: true,
    userCount: 1,
    permissions: [
      "dashboard.view",
      "orders.view", "orders.edit", "orders.cancel",
      "shipping.view", "shipping.manage",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-support",
    name: "Customer Support",
    slug: "customer_support",
    description: "Handle customer queries, view order statuses, and review submissions.",
    isSystem: true,
    userCount: 1,
    permissions: [
      "dashboard.view",
      "orders.view",
      "customers.view", "customers.edit",
      "reviews.view",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-review-mgr",
    name: "Review Manager",
    slug: "review_manager",
    description: "Moderate incoming customer reviews, approve quality testimonials, and reject spam.",
    isSystem: true,
    userCount: 0,
    permissions: [
      "dashboard.view",
      "reviews.view", "reviews.approve", "reviews.reject", "reviews.delete",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-payment-mgr",
    name: "Payment Manager",
    slug: "payment_manager",
    description: "Inspect Razorpay transactions, issue refunds, and configure payment gateways.",
    isSystem: true,
    userCount: 0,
    permissions: [
      "dashboard.view",
      "payments.view", "payments.manage",
      "orders.view",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-shipping-mgr",
    name: "Shipping Manager",
    slug: "shipping_manager",
    description: "Configure third-party shipping carriers, generate AWBs, and track courier dispatches.",
    isSystem: true,
    userCount: 0,
    permissions: [
      "dashboard.view",
      "shipping.view", "shipping.manage",
      "orders.view", "orders.edit",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
];

// ─── Admin Users ───────────────────────────────────────────────
export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    uid: "adm-venkatesh",
    email: "venkatesh@nxtvie.com",
    displayName: "Venkatesh",
    role: "super_admin",
    roleName: "Super Admin",
    avatarUrl: "/images/nxtvie/hero-model-crop.jpg",
    permissions: INITIAL_ROLES[0].permissions,
    isActive: true,
    lastLoginAt: "2026-10-01T21:40:00Z",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    uid: "adm-priya",
    email: "priya.sharma@nxtvie.com",
    displayName: "Priya Sharma",
    role: "product_manager",
    roleName: "Product Manager",
    permissions: INITIAL_ROLES[1].permissions,
    isActive: true,
    lastLoginAt: "2026-09-30T17:20:00Z",
    createdAt: "2026-02-15T00:00:00Z",
  },
  {
    uid: "adm-rajesh",
    email: "rajesh.nair@nxtvie.com",
    displayName: "Rajesh Nair",
    role: "order_manager",
    roleName: "Order Manager",
    permissions: INITIAL_ROLES[2].permissions,
    isActive: true,
    lastLoginAt: "2026-10-01T08:00:00Z",
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    uid: "adm-sneha",
    email: "sneha.p@nxtvie.com",
    displayName: "Sneha Patel",
    role: "customer_support",
    roleName: "Customer Support",
    permissions: INITIAL_ROLES[3].permissions,
    isActive: true,
    lastLoginAt: "2026-09-29T14:10:00Z",
    createdAt: "2026-04-10T00:00:00Z",
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-tshirts",
    slug: "t-shirts",
    name: "T-Shirts",
    title: "Oversized & Heavyweight Tees",
    tagline: "280 GSM luxury cotton silhouettes",
    image: "/images/products/oversized-tee-front.webp",
    isActive: true,
  },
  {
    id: "cat-jeans",
    slug: "jeans",
    name: "Jeans",
    title: "Denim & Trousers",
    tagline: "Japanese raw denim and relaxed fits",
    image: "/images/products/denim-front.webp",
    isActive: true,
  },
  {
    id: "cat-shirts",
    slug: "shirts",
    name: "Shirts",
    title: "Linen & Resort Shirts",
    tagline: "Textured weave relaxed collars",
    image: "/images/products/linen-shirt-front.webp",
    isActive: true,
  },
  {
    id: "cat-pants",
    slug: "pants",
    name: "Pants",
    title: "Cargo & Relaxed Pants",
    tagline: "Functional utility silhouettes",
    image: "/images/products/cargo-front.webp",
    isActive: true,
  },
  {
    id: "cat-sweatshirts",
    slug: "sweatshirts",
    name: "Sweatshirts",
    title: "Hoodies & Pullovers",
    tagline: "400 GSM French terry hoodies",
    image: "/images/products/hoodie-front.webp",
    isActive: true,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "cpn-welcome10",
    code: "WELCOME10",
    description: "10% off for first-time customers",
    type: "percentage",
    value: 10,
    minOrderValue: 999,
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    usageCount: 142,
    usageLimit: 1000,
    isActive: true,
  },
  {
    id: "cpn-festive500",
    code: "FESTIVE500",
    description: "Flat ₹500 off on luxury menswear orders over ₹2,999",
    type: "fixed",
    value: 500,
    minOrderValue: 2999,
    validFrom: "2026-09-01T00:00:00Z",
    validUntil: "2026-10-31T23:59:59Z",
    usageCount: 88,
    usageLimit: 500,
    isActive: true,
  },
  {
    id: "cpn-vip20",
    code: "VIP20",
    description: "Exclusive 20% discount for tier VIP members",
    type: "percentage",
    value: 20,
    minOrderValue: 4999,
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    usageCount: 23,
    usageLimit: 100,
    isActive: true,
  },
];

